
<?php echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n"; 
echo " \"http://www.w3.org/TR/html4/loose.dtd\">\n"; 
echo "	<head>\n"; 
echo "\n"; 
echo "\n"; 
echo " <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"; 
echo " <title>Eventos UCAB</title>\n"; 
echo " <link rel = \"stylesheet\" type = \"text/css\" href=\"cssinicio.css\" />\n"; 
echo " <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\n"; 
echo " integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\n"; 
echo " crossorigin=\"anonymous\">\n"; 
echo "\n";
echo " <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\n";
echo " integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\n"; 
echo " crossorigin=\"anonymous\">\n"; 
echo "</script>\n"; 
echo "\n"; 
echo " <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n"; 
echo " <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\">\n"; echo "\n"; echo " <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n"; echo " <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"; echo " <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n"; echo "	\n"; echo "	</head>\n"; echo "	<body>\n"; 
echo "	<div class=\"container well\"><!--everything on the page-->\n"; 
echo "	<div id=\"row\">\n";
echo "	<header>\n";
echo "	<center><FONT FACE=\"Serif\"><h1><text style=\"color:white\"; id=\"titulo\">EVENTOS UCAB</text></h1></FONT></center>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	<center> <div class=\"container h-100\">\n"; 
echo " <div class=\"d-flex justify-content-center h-100\">\n"; 
echo " <div class=\"searchbar\">\n"; 
echo " <input class=\"search_input\" type=\"text\" style=\"color:white\" name=\"\" placeholder=\"Buscar...\">\n"; 
echo " <a href=\"#\" class=\"search_icon\"><i class=\"fas fa-search\"></i></a>\n"; 
echo " </div>\n"; 
echo " </div>\n"; 
echo " </div></center>\n"; 
echo "\n"; 
echo "	</header>\n"; 
echo "	</div> <!--closing row 1-->\n"; 
echo "\n"; 
echo "\n";
echo "\n"; 
echo " <h2><text>Próximos eventos</text></h2>\n"; 
echo "	<div id=\"row\">\n"; 
echo "	<div id=\"row3\">\n"; 
echo "	<div class=\"six\">\n";
echo "	<br>\n";
echo "	<center><img src=\"imagen1.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"500\" height=\"236\"></center>\n";
echo "	<br>\n"; 
echo "	<a href=\"evento.html\"><center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center></a>\n"; echo "	</div><!--closing column 6-->\n";
echo "\n"; 
echo "	<div class=\"six\">\n"; 
echo "	<br>\n"; 
echo "	<center><img src=\"imagen2.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"500\" height=\"236\"></center>\n"; 
echo "	<br>\n";
echo "	<center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center>\n"; 
echo "	</div><!--closing column 3-->\n"; 
echo "\n"; 
echo "	</div>\n"; 
echo "	</div><!--closing row 3-->\n"; 
echo "\n"; 
echo " <h2><text>Otros eventos</text></h2>\n"; 
echo "\n"; 
echo "	<div id=\"row\">\n"; 
echo "	<div class=\"row4\">\n"; 
echo "	<div class=\"three\">\n"; 
echo "	<br>\n"; 
echo "	<center><img src=\"imagen3.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"240\" height=\"230\"></center>\n"; 
echo "	<br>\n"; 
echo "	<center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center>\n"; 
echo "	</div><!--closing column 3-->\n";
echo "\n"; 
echo "	<div class=\"three\">\n";
echo "	<br>\n"; 
echo "	<center><img src=\"imagen4.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"240\" height=\"230\"></center>\n"; 
echo "	<br>\n"; 
echo "	<center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center>\n"; 
echo "	</div><!--closing column 3-->\n";
echo "\n";
echo "	<div class=\"three\">\n";
echo "	<br>\n";
echo " <center><img src=\"imagen5.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"240\" height=\"230\"></center>\n"; 
echo "	<br>\n"; 
echo "	<center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center>\n"; 
echo "	</div><!--closing column 3-->\n";
echo "\n"; 
echo "	<div class=\"three\">\n"; 
echo " <br>\n"; 
echo "	<center><img src=\"imagen6.png\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"240\" height=\"230\"></center>\n"; 
echo "	<br>\n";
echo "	<center><button type=\"submit\" style='width:190px; height:40px' class=\"btn btn-primary btn-lg\">Ver más</button></center>\n"; 
echo "	</div><!--closing column 3-->\n"; 
echo "	<br>\n";
echo "	</div>\n"; 
echo "	</div><!--closing row 5-->\n";
echo "\n";
echo "<center><ul class=\"pagination pagination-lg\">\n"; 
echo " <li><a href=\"#\">1</a></li>\n"; 
echo " <li><a href=\"#\">2</a></li>\n"; 
echo " <li><a href=\"#\">3</a></li>\n"; 
echo " <li><a href=\"#\">4</a></li>\n"; 
echo " <li><a href=\"#\">5</a></li>\n"; 
echo "</ul></center>\n"; 
echo "\n"; 
echo "	</div><!--closing container div-->\n";
echo "	</body>\n";
echo "</html>\n"; 
echo "\n"; ?>
