
<?php  echo "<!DOCTYPE html>\n"; 
echo "<html>\n";
echo " <head>\n"; 
echo " <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"; 
echo " <title>JSP Page</title>\n"; 
echo " <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"; 
echo " <link href=\"css/newcss2.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"; 
echo "\n"; 
echo " </head>\n"; 
echo "\n";
echo " <body background=\"imagenes/fondo2.jpg\" > \n";
echo " \n"; 
echo " \n";
echo " <center><img style=\"float:top; margin:1px;\" alt=\"\" src=\"imagenes/mapa5.png\" width=\"70\" height=\"70\" />\n"; 
echo " </center> <font face=\"SimSun-ExtB\" size=\"7\" color=\"black\"> <center id=\"titulo2\">PackTex</center></font>\n"; 
echo " <center> <div class=\"container well\"id=\"contendor\"> \n"; 
echo "	<div id=\"registrar\">\n"; 
echo " \n"; 
echo " <div id=\"envoltura\">\n"; 
echo " \n"; 
echo "	<div id=\"contenedor\">\n"; 
echo "\n"; echo "	<div id=\"cuerpo\">\n"; 
echo "\n"; 
echo " <div class=\"form-group\">\n"; 
echo " <input name =\"nombre\" class=\"form-control input-lg\" type=\"text\" placeholder=\"Nombre\">\n"; 
echo "	\n"; 
echo " </div>\n";
echo "	<div class=\"form-group\">\n"; 
echo " <input name=\"apellido\" class=\"form-control input-lg\" type=\"text\" placeholder=\"Apellido\">\n"; 
echo "	\n"; echo "\n"; echo " </div>\n"; echo " \n"; echo "	<div class=\"form-group\">\n"; 
echo " <input name=\"correo\" type=\"email\" class=\"form-control input-lg\" id=\"exampleInputEmail1\" placeholder=\"E-mail\">\n";
echo "	\n"; 
echo " </div>\n"; 
echo "\n"; 
echo "	<div class=\"form-group\">\n"; 
echo " <input name=\"clave\" type=\"password\" class=\"form-control input-lg\" id=\"exampleInputPassword1\" placeholder=\"Clave\">\n";
echo "	\n"; 
echo " </div>\n"; 
echo " <div class=\"form-group\">\n";
echo " <input name=\"confirmar\" type=\"password\" class=\"form-control input-lg\" id=\"exampleInputPassword1\" placeholder=\"Confirmar clave\">\n"; 
echo "	\n"; 
echo " </div>\n"; 
echo "	\n"; 
echo " <a href=\"index.php\" ><button type=\"submit\" class=\"btn btn-danger btn-lg\"id=\"regresar\">Regresar</button></a>\n";
echo " <button type=\"submit\" class=\"btn btn-success btn-lg\"id=\"registrar\">Registrar</button>\n"; 
echo " \n"; 
echo "	</form>\n"; 
echo " </div>\n"; 
echo "	</div>\n"; 
echo "\n"; 
echo "	</div><!-- fin contenedor -->\n";
echo "\n"; 
echo "	</div>\n"; 
echo " </center>\n"; 
echo "</body>\n"; 
echo "\n"; 
cho "</html>\n"; 
echo "\n"; ?>
